### ISSUE TITLE
Error while running "make"

### ISSUE THREAD

**Issue by sudhakark324** [PrincetonUniversity/SCAF#4]
Need help! Stuck over this issue from last 2 weeks but couldn't get build successfull. Any help would be appreciated.

```
/cygdrive/c/Users/sudhakar/Downloads/llvm-9.0.1.src/include/llvm/ADT/FoldingSet.h:376: undefined reference to `llvm::FoldingSetNodeID::ComputeHash() const'
collect2: error: ld returned 1 exit status
make[3]: *** [lib/MemoryAnalysisModules/CMakeFiles/MemoryAnalysisModules.dir/build.make:629: lib/MemoryAnalysisModules/cygMemoryAnalysisModules-9.dll] Error 1
make[3]: Leaving directory '/cygdrive/d/P.hD/2021/SCAF-master/scaf-build-debug'
make[2]: *** [CMakeFiles/Makefile2:320: lib/MemoryAnalysisModules/CMakeFiles/MemoryAnalysisModules.dir/all] Error 2
make[2]: Leaving directory '/cygdrive/d/P.hD/2021/SCAF-master/scaf-build-debug'
make[1]: *** [Makefile:150: all] Error 2
make[1]: Leaving directory '/cygdrive/d/P.hD/2021/SCAF-master/scaf-build-debug'
make: *** [Makefile:18: scaf-debug] Error 2
```

**Comment by vgene** [comment]
Is the LLVM compiled and installed? In the linking process, we will need to link `.so` or `.dll` (for Windows) from LLVM. 
Can you post `lib/MemoryAnalysisModules/CMakeFiles/MemoryAnalysisModules.dir/link.txt` to see which LLVM path is used?

**Comment by sudhakark324** [comment]
We compiled the LLVM, and installed only LLVM-headers. The path provided by the collaborator is to find from LLVM directory which is in the downloads folder of yours.

**Comment by vgene** [comment]
Both headers and libraries are needed for compilation. The former for compiling individual object files, the latter for linking. Sorry I don't quite get the second sentence

**Comment by sudhakark324** [comment]
> Can you post lib/MemoryAnalysisModules/CMakeFiles/MemoryAnalysisModules.dir/link.txt to see which LLVM path is used?

`/usr/bin/c++.exe -std=c++17 -g   -Wl,-rpath-link,  -Wl,-O3 -Wl,--gc-sections -shared -Wl,--enable-auto-import -o cygMemoryAnalysisModules-9.dll -Wl,--out-implib,libMemoryAnalysisModules.dll.a -Wl,--major-image-version,9,--minor-image-version,0 CMakeFiles/MemoryAnalysisModules.dir/AcyclicAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/AnalysisTimeout.cpp.o CMakeFiles/MemoryAnalysisModules.dir/ArrayOfStructures.cpp.o CMakeFiles/MemoryAnalysisModules.dir/AutoRestrictAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/BasicLoopAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/CallsiteBreadthCombinator.cpp.o CMakeFiles/MemoryAnalysisModules.dir/CallsiteDepthCombinator.cpp.o CMakeFiles/MemoryAnalysisModules.dir/CallsiteSearch.cpp.o CMakeFiles/MemoryAnalysisModules.dir/ClassicLoopAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/DisjointFieldAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/FieldMallocAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/FindSource.cpp.o CMakeFiles/MemoryAnalysisModules.dir/GetCallers.cpp.o CMakeFiles/MemoryAnalysisModules.dir/GlobalMallocAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/IntrinsicAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/Introspection.cpp.o CMakeFiles/MemoryAnalysisModules.dir/KillFlow.cpp.o CMakeFiles/MemoryAnalysisModules.dir/LLVMAAResults.cpp.o CMakeFiles/MemoryAnalysisModules.dir/LoopAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/LoopVariantAllocation.cpp.o CMakeFiles/MemoryAnalysisModules.dir/NoCaptureFcn.cpp.o CMakeFiles/MemoryAnalysisModules.dir/NoCaptureGlobalAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/NoCaptureSrcAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/NoEscapeFieldsAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/PHIMazeAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/PureFunAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/RefineCFG.cpp.o CMakeFiles/MemoryAnalysisModules.dir/SCEVAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/SVFResults.cpp.o CMakeFiles/MemoryAnalysisModules.dir/SemiLocalFunAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/SimpleAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/StdInOutErr.cpp.o CMakeFiles/MemoryAnalysisModules.dir/SubloopCombinator.cpp.o CMakeFiles/MemoryAnalysisModules.dir/TraceData.cpp.o CMakeFiles/MemoryAnalysisModules.dir/TypeAA.cpp.o CMakeFiles/MemoryAnalysisModules.dir/UniquePaths.cpp.o`

**Comment by gchan510** [comment]
You don't have any of the LLVM libraries linked (most likely CMake not detecting an LLVM installation). There should be a `-Wl, -rpath, PATH_TO_LLVM_INSTALL/llvm` at the end of that file if it is being linked correctly. Are you using WSL? Building and running SCAF on Windows has never been tested and we do not support any OS that is not UNIX-like.

**Comment by gchan510** [comment]
You don't have any of the LLVM libraries linked (most likely CMake not detecting an LLVM installation). There should be a `-Wl, -rpath, PATH_TO_LLVM_INSTALL/llvm` at the end of that file if it is being linked correctly. Are you using WSL? Building and running SCAF on Windows has never been tested and we do not support any OS that is not UNIX-like.
