### ISSUE TITLE
Add Support for >= Python 3.6 

### ISSUE THREAD

**Issue by sudhakark324** [PrincetonUniversity/SCAF#5]
**Using the docker file it was installing python 3.5 and error came as given below**

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

**After that using the docker file it was installing python 3.5 and when updated the docker file to use python 3.8 then another different error came Which is given below.**

ubuntu-18@ubuntu18-VirtualBox:~/Downloads/pldi20ae_public$ sudo docker run -it d9ea89c4853c bash
root@201cbdacc33a:/home/root# python3.8 -m pip --version
pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.8)
root@201cbdacc33a:/home/root# python3.8 -m pip install /root/requirements.txt
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 267, in run
    with self._build_session(options) as session:
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 66, in _build_session
    session = PipSession(
  File "/usr/lib/python3/dist-packages/pip/download.py", line 321, in _init_
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/download.py", line 93, in user_agent
    zip(["name", "version", "id"], platform.linux_distribution()),
AttributeError: module 'platform' has no attribute 'linux_distribution'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/_main_.py", line 19, in <module>
    sys.exit(pip.main())
  File "/usr/lib/python3/dist-packages/pip/_init_.py", line 217, in main
    return command.main(cmd_args)
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 242, in main
    with self._build_session(
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 66, in _build_session
    session = PipSession(
  File "/usr/lib/python3/dist-packages/pip/download.py", line 321, in _init_
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/download.py", line 93, in user_agent
    zip(["name", "version", "id"], platform.linux_distribution()),
AttributeError: module 'platform' has no attribute 'linux_distribution'
root@201cbdacc33a:/home/root#

**Comment by gchan510** [comment]
It seems like pip dropped support for python3.5 so here's a workaround.
Please use this as the new Dockerfile:
```
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y curl

RUN apt-get install -y vim make gcc-5 g++-5 time binutils ruby python3 python3-dev python3-pip python3-matplotlib texlive-font-utils
RUN apt-get install -y gnuplot5-x11 software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update
RUN apt-get install -y python3.8 python3.8-dev python3.8-distutils python3-setuptools

RUN apt-get remove -y python3-pip
RUN python3.8 -m easy_install pip

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 10

COPY ./requirements.txt /root/requirements.txt
# RUN pip3 install --upgrade pip
RUN pip3 install -r /root/requirements.txt

RUN useradd --create-home --shell /bin/bash pldi20ae

USER pldi20ae
WORKDIR /home/pldi20ae

COPY --chown=pldi20ae ./benchmarks-public /home/pldi20ae/benchmarks
COPY --chown=pldi20ae ./CK /home/pldi20ae/CK
COPY --chown=pldi20ae ./exp_scripts /home/pldi20ae/exp_scripts
COPY --chown=pldi20ae ./llvm /home/pldi20ae/llvm
COPY --chown=pldi20ae ./scaf_lib /home/pldi20ae/scaf_lib
COPY --chown=pldi20ae ./README.txt /home/pldi20ae/README.txt
COPY --chown=pldi20ae ./LICENSE.public /home/pldi20ae/LICENSE
COPY --chown=pldi20ae ./bashrc /home/pldi20ae/bashrc
COPY --chown=pldi20ae ./.cache /home/pldi20ae/.cache

RUN cat /home/pldi20ae/bashrc >> /home/pldi20ae/.bashrc
RUN rm /home/pldi20ae/bashrc

CMD /bin/bash
```
And change `ck>=1.11.4` to `ck==1.11.4` in requirements.txt

**Comment by sudhakark324** [comment]
### matplotlib is installed with version 1.5.1. But it is creating problem. Showing the name=module, err=No module named 'matplotlib._path')!

```
ubuntu-18@ubuntu18-VirtualBox:~/Downloads/pldi20ae_public$ sudo docker run -it --memory=8gb --memory-swap=-1 pldi20ae_scaf:1.0
pldi20ae@f412b2777c82:~$ python3.8 -m pip list
Package             Version
------------------- -----------------------
ck                  1.11.4
cycler              0.9.0
joblib              1.0.1
**matplotlib          1.5.1**
numpy               1.20.2
Pillow              3.1.2
pip                 21.0.1
pycurl              7.43.0
pygobject           3.20.0
pyparsing           2.0.3
python-apt          1.1.0b1+ubuntu0.16.4.11
python-dateutil     2.4.2
pytz                2014.10
scipy               1.6.2
setuptools          20.7.0
six                 1.10.0
termcolor           1.1.0
unattended-upgrades 0.1
utils               1.0.1
wheel               0.29.0
pldi20ae@f412b2777c82:~$ ck run artifact --test
/home/pldi20ae/exp_scripts/GetDep.py:136: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if(words[6] is not 'NaN'):
CK error: [artifact] can't load module code (path=/home/pldi20ae/CK/pldi20-ae/module/artifact, name=module, err=No module named 'matplotlib._path')!
pldi20ae@f412b2777c82:~$ 
```

**As it can be clearly seen matplotlib is installed with version 1.5.1. But it is creating problem.**

**Comment by sudhakark324** [comment]
Respected Sir
Please help.
There is an error listed below.....
matplotlib is installed with version 1.5.1. But it is creating problem.
Showing the name=module, err=No module named 'matplotlib._path')!

***@***.***VirtualBox:~/Downloads/pldi20ae_public$ sudo docker
run -it --memory=8gb --memory-swap=-1 pldi20ae_scaf:1.0
***@***.***:~$ python3.8 -m pip list
Package             Version
------------------- -----------------------
ck                  1.11.4
cycler              0.9.0
joblib              1.0.1
**matplotlib          1.5.1**
numpy               1.20.2
Pillow              3.1.2
pip                 21.0.1
pycurl              7.43.0
pygobject           3.20.0
pyparsing           2.0.3
python-apt          1.1.0b1+ubuntu0.16.4.11
python-dateutil     2.4.2
pytz                2014.10
scipy               1.6.2
setuptools          20.7.0
six                 1.10.0
termcolor           1.1.0
unattended-upgrades 0.1
utils               1.0.1
wheel               0.29.0
***@***.***:~$ ck run artifact --test
/home/pldi20ae/exp_scripts/GetDep.py:136: SyntaxWarning: "is not" with
a literal. Did you mean "!="?
  if(words[6] is not 'NaN'):
CK error: [artifact] can't load module code
(path=/home/pldi20ae/CK/pldi20-ae/module/artifact, name=module, err=No
module named 'matplotlib._path')!
***@***.***:~$

As it can be clearly seen, matplotlib is installed with version 1.5.1. But
it is creating problems.







*--Thanks & Regards,Sudhakar Kumar,Ph.D. Scholar,Reg No.-2017-EZ-154Panjab
University.*

**Comment by vgene** [comment]
It seems like a matplotlib version issue, try this in the terminal:

```
pip3 install --upgrade matplotlib
```

Source: https://stackoverflow.com/questions/30196585/matplotlib-import-error-no-module-named-path/46639542
